### PR TITLE
ordering technical properties

### PR DESCRIPTION
**Pull request by bellerophons-pegasus**
Added high ordering numbers for technical properties

### CODE REVIEW

**Review by nczirjak-acdh — APPROVED** [review]

**Review by zozlak — APPROVED** [review]

**Comment by carlonim** [comment]
Should we give an ordering number to `acdh:hasBinaryUpdatedDate` too?

**Review by carlonim — CHANGES_REQUESTED** [review]
Should we give an ordering number to `acdh:hasBinaryUpdatedDate` too?

**Comment by carlonim** [comment]
For example, now we have this sequence:
* `hasBinaryUpdatedRole` 940
* `hasFilename` 941
* `hasHash` 942
* `hasRawBinarySize` 943
* `hasUpdatedRole` 944

We might fit `hasBinaryUpdatedDate` in this sequence, maybe just after `hasBinaryUpdatedRole`, like this:
* `hasBinaryUpdatedRole` 940
* `hasBinaryUpdatedDate` 941
* `hasFilename` 942
* `hasHash` 943
* `hasRawBinarySize` 944
* `hasUpdatedRole` 945

**Comment by bellerophons-pegasus** [comment]
Oh, `hasBinaryUpdatedDate` escaped me.

**Review by carlonim — APPROVED** [review]

**Review by nczirjak-acdh — APPROVED** [review]

**Pull request merged**
